elixir-wallaby/wallaby

- lib/wallaby/dsl/navigation.ex
- test/wallaby/dsl_test.exs
It'd be nice not to have to write out the full url on each `visit`. In test_helper.exs:
```
{:ok, _} = Application.ensure_all_started(:wallaby)
Application.put_env(:wallaby, :base_url, Allocations.Endpoint.url)
```
then `visit("/sign_in")` would navigate to http://localhost:4001/sign_in.
> Prepend base url to request path

- config/config.exs
- lib/wallaby/dsl/finders.ex
- lib/wallaby/dsl/helpers.ex
Allow maximum wait times to be configurable. This allows for extended wait times on slow boxes (like on ci servers)
> Make wait time configurable

- lib/wallaby/node.ex
- test/wallaby/node_test.exs
Clears out the node before we call fill_in. Semantically fill_in should not append to the text in the input.
Closes #18
> Clear the text from the node before its filled in

- lib/wallaby/exceptions.ex
- lib/wallaby/node.ex
- test/wallaby/node_test.exs
We can use these matchers to assert that dom elements are visible or no longer visible. They also block the page until they either become true or until the max wait time is reached which means they can be used to help with async tests.
Closes #13
> Matches has_css? and has_no_css?

- README.md
These sandbox methods aren't in the latest published version, 1.1.5.
(Can be updated once Ecto 2.0.0 final is out)
> Add note about version of Ecto required

- lib/wallaby/driver.ex
- lib/wallaby/node.ex
- lib/wallaby/xpath.ex
- test/support/pages/wait.html
- test/wallaby/node_test.exs
Finders should only return visible elements by default.
If this needs to be overwritten for some reason then a `visible: false` option can be passed to the finder like so: `find(session, ".some_element", visible: false)`.
The correct solution for determining visibility is to either use the webdriver standard `get_element_rect` or to query for the element and then get the bounding rectangle for the element. If its 0 then the element isn't visible. However, Phantom doesn't implement the `rect` endpoint. Instead it implements the `size` endpoint and (conveniently) a `displayed` endpoint. I've left all 3 solutions in for now. I'd like to consolidate and clean this up by moving some of this logic to a phantom specific driver so that its at least isolated. But that can be future work once we …
> Only find visible elements by default

- config/config.exs
- lib/wallaby/driver.ex
- lib/wallaby/node.ex
- test/wallaby/session_test.exs
This fixes some of the intermittent failures that we've been seeing in the internal test suite.
The issue was that the Session test was set to `async: true`. However, one of the tests in that test case mutates global Application state (by setting an config value as part of a test). The test was changing the `:base_url` config value for the application. Because it was running async other tests had the possibility of running while that config value was set. The issue was that test would then try to navigate to a route like `http://localhost:1234/http://localhost:1235/page_1.html` or something similar. Since that route doesn't exist it can't ever find anything. I'm not sure if there's a better way to handle errors like that. The page never loads since it doesn't exist. But I'm not sure if we …
> Fix intermitent errors

- lib/wallaby/node.ex
Provide a default wait time if one isn't specified in the Application config.
> Provide a default max wait time.

- README.md
- lib/wallaby.ex
- lib/wallaby/driver.ex
- lib/wallaby/exceptions.ex
- lib/wallaby/metadata.ex
- lib/wallaby/phantom.ex
- test/wallaby/metadata_test.exs
The phoenix_ecto sandbox plug now accepts metadata inside the user agent string (see phoenixframework/phoenix_ecto#44). We can use that to pass db ownership information back to Phoenix and Ecto.
> Use new ecto sandbox metadata api

- lib/wallaby/session.ex
- test/wallaby/session_test.exs
Session can now keep track of any screenshots that have been taken. This should make chaining screenshots easier because we're now returning a proper session struct.
Closes #37.
> Populate a list on the session when taking screenshots

- lib/wallaby/exceptions.ex
- lib/wallaby/session.ex
- test/wallaby/session_test.exs
Supplying a relative url when there is no base_url set can result in some opaque errors. Instead we can just return a well defined error to the user with instructions on how to set up a base_url.
Closes #36.
> Raise exception is there is no base_url set

- README.md
I found I needed the `:sql_sandbox` config in my `config/test.exs` rather than the test helper. This is because the endpoint is compiled by the time the test helper is run and so doesn't see the setting. Without this I got the `(RuntimeError) cannot find ownership process ` error.
> Fix setup documentation

- README.md
Manually checking out connections currently doesn't work for things like making a query from a `FooChannel.join` callback or a background job so you can't run your tests async in these cases. Having the `unless tags[:async]` bit in the AcceptanceCase matches what Phoenix does and allows you to quickly toggle between async and sync when you run into this.
> Add shared config to AcceptanceCase in README

- lib/wallaby/node.ex
- test/wallaby/node_test.exs
The choose action should return the session instead of the node so that it can be chained properly.
> Return the session from the choose action

- README.md
BTW I don't know whether there is a community solution for that, but every library seems to specify the version number in the README and it's quite easy to forget to update it in the README while doing a release.
> Update version in README to 0.7.0

- README.md
- lib/wallaby.ex
- lib/wallaby/driver.ex
- lib/wallaby/node/query.ex
- lib/wallaby/session.ex
- test/wallaby/session/navigation_test.exs
- test/wallaby/session/screenshot_test.exs
- test/wallaby/session_test.exs
Users can now specify the screenshot directory. This should allow for taking screenshots on CI servers. Along with that we can tell Wallaby to automatically take screenshots on any failure.
> Extra screenshot support

- .travis.yml
- lib/wallaby/exceptions.ex
- lib/wallaby/node/query.ex
- test/support/pages/page_1.html
- test/wallaby/node/query_test.exs
- test/wallaby/node_test.exs
If an element should have been invisible but wasn't we still threw the "element is invisible" error which was confusing.
> Throw correct error for finding visible elements

- lib/wallaby/driver.ex
- lib/wallaby/exceptions.ex
- lib/wallaby/node.ex
- lib/wallaby/node/query.ex
- test/support/pages/forms.html
- test/wallaby/node/query_test.exs
Wallaby will now throw an error if a user tries to find a button that doesn't have a type attribute.
> Return errors if buttons are missing types.

- lib/wallaby/helpers/key_codes.ex
- lib/wallaby/session.ex
- test/wallaby/helpers/key_codes_test.exs
I ran into the need to send an `enter` key as part of an acceptance test. There wasn't any documentation within `Session.send_keys/2` about how it worked or how keys should be defined. This is a basic attempt at adding documentation to highlight that key code conversion if a feature, and hopefully lead future devs to the right part of the source code.
> Document usage of send_keys and KeyCodes

- lib/wallaby/dsl/actions.ex
- test/support/pages/forms.html
- test/wallaby/dsl/actions/fill_in_test.exs
Fill in throws an error is the input isn't a string. This allows fill_in to accept numbers and convert them into binaries before filling in the field.
> Allow numbers to be passed to fill_in

- README.md
Got bitten by that when starting to use wallaby. Ported this line straight from the `phoenix_ecto` docs.
> Add note on position of sandbox plug

- lib/wallaby/driver.ex
This fixes the issue with httpoison timeouts and instead lets Wallaby handle
the timeouts explicitly.
Closes #74.
> Set HTTPoison recv timeout to infinity

- lib/wallaby.ex
- test/wallaby/driver/configuration_test.exs
- test/wallaby/driver/js_errors_test.exs
It was impossible to disable javascript errors being re-thrown in Wallaby because we were using `||` instead of the default value in `Application.get_env/3`. This PR fixes that issue.
> Fix issue with disabling js-errors

- lib/wallaby.ex
- lib/wallaby/server.ex
Increases timeout from 5000ms to :infinity. In
environments with a low pool size, e.g. CI workers
and lesser powered laptops, test failures due to a
delay > 5000ms in checking out a worker from the
pool frequently occur. As ExUnit has a default max
time for a test case to complete (60_000ms), it
makes sense to avoid these failures by allowing
a test to block until a worker is checked back in
to the pool.
> Increases gen_server:call timeout to :infinity

- lib/wallaby/session.ex
Without the milliseconds, screenshots were overwriting each other when they occurred too quickly.
> Use the system time for screenshot names

- lib/wallaby/node/query.ex
- test/support/pages/forms.html
- test/support/pages/wait.html
- test/wallaby/dsl/actions/click_button_test.exs
The logic for finding incorrect buttons was incorrect. This PR adds better tests and fixes the broken logic. Specifically buttons with no type attribute or an invalid type attribute will always return `submit` as their type. To get around this we simply check to see that there is a button that could have matched and then skip any type checking on the button element itself.
> Incorrect logic for finding buttons with missing types

- lib/wallaby/node/query.ex
- test/support/pages/page_1.html
- test/wallaby/dsl/finders/find_test.exs
Text filtering needs to use a regex match instead of a string. That way if there is other text inside of the element we can still provide scoping
> Fix text filtering

- lib/wallaby/node/query.ex
- lib/wallaby/xpath.ex
- test/support/pages/forms.html
- test/support/pages/select_boxes.html
- test/wallaby/dsl/actions/check_test.exs
- test/wallaby/dsl/actions/choose_test.exs
- test/wallaby/dsl/actions/click_button_test.exs
- test/wallaby/dsl/actions/file_test.exs
- test/wallaby/dsl/actions/fill_in_test.exs
- test/wallaby/dsl/actions/select_test.exs
Switching to double quotes so that single quotes can be used in xpath queries. In the future this should be solved more completely by using xpath concatenation.
> Escape xpath quotes

- lib/wallaby/server.ex
- test/wallaby/phantom/configure_test.exs
- test/wallaby/server_test.exs
To better isolate tests, I thought it would be a good idea for each PhantomJS process to have its own local storage directory.
> Separate local storage per phantom

- lib/wallaby.ex
- lib/wallaby/driver.ex
- lib/wallaby/phantom.ex
- lib/wallaby/server.ex
- lib/wallaby/session.ex
- test/wallaby/integration/local_storage_test.exs
Local Storage was being shared across sessions because it wasn't being cleared when a session was closed.
> Ensure that local storage isn't shared across sessions.

- README.md
- config/config.exs
- lib/wallaby.ex
- lib/wallaby/phantom/logger.ex
- test/wallaby/phantom/logger_test.exs
Users should be able to disable javascript console logs (or redirect logs to a file instead of `:stdio`).
Fixes #115.
> Allow js logs to be disabled or redirected to a file.

- lib/wallaby.ex
- lib/wallaby/node.ex
- lib/wallaby/node/query.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
- lib/wallaby/phantom/log_store.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/session.ex
- test/wallaby/phantom/configure_test.exs
- test/wallaby/phantom/driver/configuration_test.exs
- test/wallaby/phantom/driver/js_errors_test.exs
- test/wallaby/phantom/log_store_test.exs
- test/wallaby/phantom/server_test.exs
This change is an important initial refactor for adding support for selenium. This moves the existing server and driver modules underneath `phantom` and updates the supervisor tree to reflect that change.
This PR fixes https://github.com/keathley/wallaby/projects/1#card-707678
> Move driver and server under the phantom namespace

- lib/wallaby/exceptions.ex
- lib/wallaby/node/query.ex
- lib/wallaby/xpath.ex
- test/support/pages/forms.html
- test/wallaby/dsl/actions/click_button_test.exs
The default value for `type` is `submit`:
https://w3c.github.io/html/sec-forms.html#element-attrdef-button-type
> Allow clicking on buttons with no type

- lib/wallaby.ex
- lib/wallaby/node.ex
- lib/wallaby/node/query.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/session.ex
- mix.exs
Elixir 1.4 gives warnings like the following:
```
warning: variable "driver" does not exist and is being expanded to "driver()",
please use parentheses to remove the ambiguity or change the variable name
lib/wallaby.ex:25
```
> Fix parentheses warnings for Elixir 1.4

- lib/wallaby/browser.ex
> Make `Browser.click/2` return the parent element

- lib/wallaby/browser.ex
- lib/wallaby/dsl.ex
- lib/wallaby/element.ex
- lib/wallaby/session.ex
- test/wallaby/browser/assert_text_test.exs
- test/wallaby/browser/has_text_test.exs
I have moved the functionality specific to elements to the `Element` module. I've also added deprecation warnings for the pieces of the api that are going to be removed after the 0.16 release.
> Element modules and deprecation warnings

- lib/wallaby/browser.ex
- lib/wallaby/element.ex
- lib/wallaby/phantom/driver.ex
- test/wallaby/element/send_keys_test.exs
Moving `send_keys/2` and `value/1` to the element module. I've also eliminated the need to explicitly click the element before sending the keys.
> Send keys works with both sessions and elements.

- lib/wallaby/browser.ex
- lib/wallaby/element.ex
Opts could throw an error when used in the deprecation warnings. Added an `inspect` to make sure that everything works correctly.
> Inspection in deprecation warnings

- README.md
The original phantomjs package is deprecated and replaced by
phantomjs-prebuilt.
Deprecation notice from the package page:
DEPRECATED
Pre-2.0, this package was published to NPM as phantomjs.
We changed the name to phantomjs-prebuilt at the request of PhantomJS team.
Please update your package references from phantomjs to phantomjs-prebuilt
> Use new phantomjs package

- lib/wallaby/phantom/server.ex
- test/wallaby/phantom/configure_test.exs
Wallaby was unable so spawn the subprocess when the project path contains a space.
Additional quoting added by using the args option.
> quote arguments to script, use spawn_executable

- lib/wallaby/browser.ex
- lib/wallaby/dsl.ex
- lib/wallaby/query/error_message.ex
- test/wallaby/browser/assert_refute_has_test.exs
* fixes #159
* implemented as macros as it results in a cleaner stack trace
This is also the first time I write a macro for production code, so feel free to review away :)
----
As for macro vs. function I tried out a quick version in our project (different implementation than here, hence less cool error message) and the stack trace is just cleaner:
Function:
```
1) test logging in logging successfully (Fulfillment.AuthAcceptanceTest)
test/acceptance/auth_acceptance_test.exs:5
Expected truthy, got false
code: has?(parent, query)
stacktrace:
(fulfillment) lib/wallaby_helpers.ex:20: WallabyHelpers.assert_has/2
test/acceptance/auth_acceptance_test.exs:12: (test)
```
Macro:
```
1) test logging in logging successfully (Fulfillment.AuthAcceptanceTest)
test/acceptance/auth_acceptance_test.exs:5 …
```
> Implement assert_has and refute_has

- lib/wallaby/browser.ex
- test/wallaby/browser/clear_test.exs
- test/wallaby/browser/click_button_test.exs
- test/wallaby/browser/fill_in_test.exs
A first step toward #177 
As this is the first one I thought I'd keep it small and simple (I just started with the first function that had an `IO.warn` in there) so we can see if this is a good template for removing outdated functions :)
> Remove deprecated functions - fill_in

- .travis.yml
- lib/wallaby/browser.ex
- lib/wallaby/element.ex
- lib/wallaby/phantom/server.ex
- mix.exs
These changes fix a few dialyzer errors in the project and also run dialyzer during the Travis CI build. I made a couple notable changes below
I removed the typespec from the `assert_has` and `refute_has` macros, because dialyzer was raising a warning on them. I checked in the Elixir, Ecto, Plug and Phoenix libraries and couldn't find a single example of where someone documented macros using a typespec.
I also changed the call to `Port.open/2` so it passes a charlist as the second element in the `{:spawn_executable, _}` tuple. This call passed directly to the `open_port/2` erlang function and expects an erlang string.
Please let me know what you think and if there's any changes you'd like me to make.
> Fix dialyzer errors and add dialyzer to build

- lib/wallaby/browser.ex
- test/wallaby/browser/execute_script_test.exs
- test/wallaby/browser/local_storage_test.exs
This resolves #172 by changing ```execute_script``` to return the session passed to it and allowing a callback to be passed to ```execute_script```  which has the script's return value as its parameter.
> make execute_script return session instead of script result

- .travis.yml
* Example: https://travis-ci.org/keathley/wallaby/jobs/218338365
* not sure what's happening... timeout maybe?
Checking 380 modules in dialyxir_erlang-19.2_elixir-1.4.0_deps-dev.plt
Adding 265 modules to dialyxir_erlang-19.2_elixir-1.4.0_deps-dev.plt
/home/travis/.travis/job_stages: line 53:  2871 Killed                  mix dialyzer --plt
The command "mix dialyzer --plt" failed and exited with 137 during .
Any idea @aaronrenner ?
> Removed due to travis fails

- lib/wallaby/session.ex
I just ran the tests and session.id is a uuid string, not an integer. Here is a sample session struct I received when running the test suite.
```
%Wallaby.Session{id: "9ae736b0-1958-11e7-9573-6f21b8c89bef", screenshots: [],
server: #PID<0.228.0>,
session_url: "http://localhost:59483/session/9ae736b0-1958-11e7-9573-6f21b8c89bef",
url: "http://localhost:59483/session/9ae736b0-1958-11e7-9573-6f21b8c89bef"}}
```
> Fix typespec for Session struct

- .travis.yml
This runs the build with `sudo: required` so it runs on a larger vm with [7.5GB of memory](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), so mix dialyzer --plt doesn't run the vm out of memory and exit with code 137.
This also runs wraps the `mix dialyzer --plt` in the `travis_wait` command so if it doesn't output any log statements in 10 minutes, the build won't timeout.
Finally, the build is already being cached, so the only time the PLT needs to be built is on a fresh cache, or if the build matrix is changed.
Fixes #186.
> Fix dialyzer on travis ci

- .travis.yml
Being up to date with the good ol patch levels.
Which reminds me, is there a reason we don't just run both elixir versions against both otp releases? Being very nice to travis? :) @keathley
> Update elixir versions in .travis.yml

- lib/wallaby/phantom/server.ex
- priv/run_phantom.sh
This allows Wallaby.Phantom.Server to run when priv/run_phantom.sh isn't available (like when running as an escript). Since we can't directly run the script, we need to run /bin/sh with the arguments we want to use and pipe the contents of run_phantom.sh in via stdin. This is almost the
same script as in the Elixir Port docs (https://hexdocs.pm/elixir/Port.html#module-zombie-processes), but it runs the command in the background and then listens for stdin to close
and kills the process from a subshell.
I have confirmed this shuts down phantom in the following situations:
* ^C+^C in IEx
* causing the beam to core dump by overflowing the atom table
* running kill -9 on the beam.
Huge thanks to @koudelka for all of his help coming up with this approach. Please let me know if you see any areas …
> Make Phantom.Server escript compatible

- test/wallaby/browser/stale_nodes_test.exs
I was curious what the response looked like from PhantomJS when we get a StaleReferenceException found out we didn't have a test triggering it.
> Test to ensure StaleReferenceException is raised

- lib/wallaby/phantom/driver.ex
- test/wallaby/phantom/driver_test.exs
I have seen this issue with BrowserStack returning 204 status codes when calling the /visit command on their Android 4.0 and 4.1 browsers. This change prevents wallaby from crashing because there is no JSON to parse on a 204 status code.
> Don't parse JSON on 204 status codes

- lib/wallaby/browser.ex
Since browser uses opaque types, dialyzer was giving me the following error with this code: `session |> visit("http://example.com") |> find(Query.css("#my-id"))`
```
lib/trusted_form_smoke_tester/integration_tests/trusted_form_page.ex:60: The call 'Elixir.Wallaby.Browser':find(session@1::#{'__struct__':='Elixir.Wallaby.Session', 'driver':=atom(), 'id':=binary(), 'screenshots':=[any()], 'server':='nil' | pid(), 'session_url':=binary(), 'url':=binary()},#{'__struct__':='Elixir.Wallaby.Query', 'conditions':=[{atom(),_}], 'html_validation':='nil', 'method':='css', 'result':=[], 'selector':=_}) does not have an opaque term of type 'Elixir.Wallaby.Browser':element() | 'Elixir.Wallaby.Browser':session() as 1st argument
```
This switches `Browser.visit/2` to return the opaque type.
> Fixes typespec for Browser.visit/2

- lib/wallaby.ex
- lib/wallaby/browser.ex
- lib/wallaby/driver.ex
- lib/wallaby/element.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
- lib/wallaby/query.ex
- lib/wallaby/session.ex
This moves the responsibility for determining the Wallaby driver to use to the Session and removes all of the hard-coded references to `Wallaby.Phantom.Driver`.
I also created a `Wallaby.Driver` behavior which new drivers will need to implement. I left this behavior with `@moduledoc false` in case we wanted to adjust the interface before making it public. Also, I'm thinking the ideal api for `Wallaby.start_session/1` will be:
```elixir
Wallaby.start_session(driver: Wallaby.Selenium, remote_url: "http://...")
```
instead of 
```elixir
Wallaby.start_session(driver: Wallaby.Selenium.Driver, remote_url: "http://...")
```
which is why I've delegated all of those functions in `Wallaby.Phantom`.
> Move current driver into Wallaby.Session

- README.md
- config/config.exs
- lib/wallaby/phantom/driver.ex
I was having an issue where BrowserStack wasn't sending me a response on some of my commands, causing my script to just hang. This change will allow me to override the hackney options and set custom timeouts.
> Allow adjusting hackney options

- integration_test/support/test_server.ex
- lib/wallaby.ex
- lib/wallaby/dsl.ex
- lib/wallaby/helpers/key_codes.ex
- lib/wallaby/metadata.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
- lib/wallaby/phantom/log_store.ex
- lib/wallaby/phantom/logger.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/query/error_message.ex
- lib/wallaby/query/xpath.ex
- lib/wallaby/session.ex
This removes quite a few modules from the API docs that aren't meant for public usage. This will allow us to know exactly what functions people depend on and which ones we need to consider backward compatibility on. Here's what the API docs look like now.
There's still quite a few of deprecated functions in `Wallaby.Browser` that need to be removed, but I figured they will be taken care of as part of #177.
> Only document modules for public API

- integration_test/cases/query_test.exs
- test/wallaby/query_test.exs
`Wallaby.Integration.QueryTest` was starting a ton of sessions and not cleaning them up. This switches it over to use `Wallaby.Integration.SessionCase` and uses the session that's automatically created and cleaned up. I also extracted the unit tests out of this integration test so they can be run separately.
I'm also thinking this should help the reliability of my tests for #198.
> Fix leaking webdriver sessions in QueryTest

- integration_test/cases/browser/local_storage_test.exs
- integration_test/cases/wallaby_test.exs
- integration_test/support/session_case.ex
- integration_test/tests.exs
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
There's a few changes in here:
1. Added an integration test that ensures the driver allows calling `Wallaby.end_session/1` on a closed session. There was an issue in the phantom driver where the check_logs call would fail during end_session, so I added an option to skip checking logs. (I was getting a 404 `Variable Resource Not Found` response from phantom when it tried to check logs while clearing local storage during shutdown. I'm wondering if there's some async stuff going on here and if shutdown got in the way).
2. Set up an `on_exit` callback directly in `start_test_session`, so sessions created through this function are automatically shut down when the test exits.
3. Added a tag to `Wallaby.Integration.SessionCase` that allows us to be able to skip automatically generating a test …
> Automatically clean up sessions created with start_test_session/1

- integration_test/cases/browser/stale_nodes_test.exs
- integration_test/support/pages/stale_nodes.html
This PR fixes an unreliable test for stale nodes. Instead of using Proces.sleep I'm using `assert_has` to force the DOM to block until the node has been removed.
> Fix issue with removing stale nodes from the DOM.

- integration_test/cases/browser/execute_script_test.exs
- integration_test/cases/browser/find_test.exs
- integration_test/cases/browser/text_test.exs
- lib/wallaby/browser.ex
Removes the deprecated version of text. If you need to get the text of an Element you can do so by specifying `Element.text`.
I did question whether the session version of the function should be on `Browser` or `Element`. I see arguments for either. I left it on `Browser` for now but I'm open to other ideas.
> Remove deprecated version of text

- integration_test/cases/browser/clear_test.exs
- lib/wallaby/browser.ex
This removes the deprecated versions of clear from the Browser module.
> Remove deprecated versions of clear.

- integration_test/cases/browser/file_test.exs
- lib/wallaby/browser.ex
Last one of the day. Removes the deprecated clauses for attach_file.
> Remove deprecated attach_file

- .tool-versions
- .travis.yml
* also found out there is an erlang 18.3.4 which we can run against
* made it a proper crossover matrix with all elixir versions against
all erlang versions - thank you travis sorry for the load :)
> Run against Erlang 19.3 & 18.3

- integration_test/cases/browser/click_button_test.exs
In the [fixtures](https://github.com/keathley/wallaby/blob/81d69ea/integration_test/support/pages/forms.html#L43-L44), this button's text is actually _button with no type_. The current text (_Submit button_) selects an element which belogs to [another](https://github.com/keathley/wallaby/blob/81d69ea/integration_test/cases/browser/click_button_test.exs#L48) test case: _clicking button type[submit] via button text_.
> Fix test case for a button with no type via text

- integration_test/cases/browser/click_test.exs
- integration_test/support/pages/forms.html
- lib/wallaby/browser.ex
This is similar to the issue with finding duplicate buttons. We're incorrectly reporting malformed labels when its really an issue with finding an incorrect amount of elements. This is noticeable when finding radio buttons and checkboxes.
> Report duplicate html issues correctly.

- integration_test/cases/browser/visible_test.exs
- lib/wallaby/browser.ex
This PR removes the deprecated version of `visible?`.
> Remove deprecated version of visible?

- lib/wallaby/browser.ex
Removes `checked?` from the `Browser` module.
> Remove checked?

- integration_test/cases/browser/click_button_test.exs
- lib/wallaby/browser.ex
Removes the deprecated versions of `click` and `click_on`.
> Remove deprecated versions of click.

- lib/wallaby/browser.ex
Removes `send_text` from `Browser`.
> Remove send_text

- integration_test/cases/browser/click_button_test.exs
- integration_test/support/pages/forms.html
- lib/wallaby/browser.ex
If there are duplicate buttons then Wallaby will incorrectly return an error saying that the button has a bad type. But the real error is that the specified count is incorrect. This PR adds a test for this case and fixes the underlying bug.
> Fix bad button type error reporting.

- integration_test/cases/browser/visible_test.exs
- integration_test/support/pages/page_1.html
* Follow up to #229
* @aaronrenner mentioned that it doesn't work on selenium either
so not much sense in keeping it around sadly
> Remove obscured test case as not working with phantom and selenium

- integration_test/cases/browser/select_test.exs
- lib/wallaby/browser.ex
This PR removes the `select` functions and `selected?/1` from the Browser module. It would be very nice to have some sort of query composition for finding options inside of a given select. Because there are multiple "Option 2" options on the page you get a duplicate element error if you don't scope everything to the specific select.
> Remove select and selected?/1 from Browser module.

- README.md
The example has a class of `.users` instead of `users`
> Fix example html `users` class

- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- test/wallaby/experimental/selenium/webdriver_client_test.exs
I was running wallaby + selenium against Browserstack and saw this issue when testing on iPad 2 (ios 5.0). This also adds a few more typespecs.
> Fixed issue when no value field in response

- integration_test/cases/browser/invalid_selectors_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/element.ex
- lib/wallaby/exceptions.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- lib/wallaby/phantom/driver.ex
- lib/wallaby/query/error_message.ex
- test/wallaby/experimental/selenium/webdriver_client_test.exs
- test/wallaby/phantom/driver_test.exs
This PR allows us to capture invalid element state errors coming from the driver. Typically you see this if you try to use an element state selector incorrectly. I noticed it when I accidentally typoed this selector:
```
css(".checkbox-group .checkbox input[data-size-id-toggle=\"#{size}\"]:checkbox")
```
`:checkbox` isn't a valid state. I meant to say `:checked`. We don't handle this gracefully. Instead it just dumps the stack trace. I've changed it to provide better feedback to the user.
Currently this only checks the error in `assert_has` which is where I noticed it. I still need to add tests to make sure that this error isn't present in `find` as well. I'm also considering throwing the error from the driver. It seems like if we see this error we want to stop since retrying won't do the …
> Capture invalid element state errors.

- integration_test/support/session_case.ex
- lib/wallaby.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/chrome/chromedriver.ex
- lib/wallaby/session_store.ex
This is the same logic that we use to kill chrome sessions. I've generalized it and made it work for all browsers. The solution is to monitor the processes the starts a session. If we detect a DOWN signal from that process then we kill the session ourselves. If the process calls `end_session` then we demonitor the process and allow wallaby to close the session.
This should fix #269 and #174.
> Monitor and demonitor sessions for all browsers.

- lib/wallaby/query/error_message.ex
- test/wallaby/query/error_message_test.exs
We didn't have a matching function for displaying text query errors.
This fixes #283
> Add the correct error message for text queries

- .travis.yml
Right now we generate [40](https://travis-ci.org/keathley/wallaby/builds/257458811) travis builds. That is a bit too much, I don't want my Travis friends to come over and be like "Tobi, you are using up all our resources!"
On a more serious note, we should fairly use our given free resources. Also, we sometimes have weird troubles downloading drivers etc. (which we should try to fix) but the more builds we have the more likely this is to occur and then we gotta restart etc... also, of course - it takes quite long.
So, of all the things we test what can we let go off?
* We need to test all drivers
* we need to test all elixir versions
* We need to test all combinations of drivers and elixir versions as they might execute different code from our driver integration and I wanna avoid issues …
> Reduce number of travis builds

- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
Hi Chris,
As per our chat earlier, I Implemented the following:
```elixir
accept_alert/2, dismiss_alert/2, accept_confirm/2,
dismiss_confirm/2, accept_prompt/3, dismiss_prompt/2
```
And the following tests, are all passing:
```sh
WALLABY_DRIVER=chrome mix test integration_test/cases/browser/dialog_test.exs:96
WALLABY_DRIVER=chrome mix test integration_test/cases/browser/dialog_test.exs:111
WALLABY_DRIVER=chrome mix test integration_test/cases/browser/dialog_test.exs:139
WALLABY_DRIVER=chrome mix test integration_test/cases/browser/dialog_test.exs:164
``` 
However, there is a caveat: 
- can't open a dialog/alert/prompt in ChromeDriver 2.30.477690, when in headless mode (OSX here). Probably it works,  if using Xvfb ... but it sucks :/
The tests above and the implementation so far, work with …
> Handle alerts in chrome #277

- lib/wallaby/phantom.ex
> Prevents failing if phantomjs is not on PATH, but configured manually

- mix.exs
I just had some trouble upgrading wallaby due to our minor level strict dependency on httpoison, I think we should be good just relying on the minor. Wdyt?
> Relax httpoison dependncy

- .gitignore
- .tool-versions-e
`.tool-versions-e` is just a backup file created by asdf when changing dependency versions. This file can be safely ignored from version control.
> Remove backup .tool-versions-e file

- integration_test/cases/browser/navigation_test.exs
- lib/wallaby/browser.ex
- test/support/settings_test_helpers.ex
- test/wallaby/browser_test.exs
I noticed in #300 that `visit/2` is generating urls like http://localhost:54579//logs.html that have too many slashes. This occurs when the base_url has a trailing slash and the requested path has a leading slash. This change adds tests and fixes the issue so we don't end up with urls with too many or not enough slashes depending on how these settings are configured.
> Fixes visit/2 issue where urls have too many slashes

- lib/wallaby/query.ex
- test/wallaby/query_test.exs
Feedback very welcome! This is stuff I'd often look up myself by compiling queries while working with wallaby :)
Honestly: I'm not the best at xpath ;P So theoretically I might have gotten some of those wrong.
Some ideas/thoughts:
* Not sure if the attributes should be like they are atm e.g. id or if it should be in ` e.g. `id`
* I had thought about including a doc test that shows a compiled query (I just looked at those when I wrote these) - might help for people, might be too much - my biggest fear is that we'd basically have to adjust these tests every time we change how something is compiled which sounds like a medium big manual churn.
Doc writing style etc. can gladly be commented on, nut sure if all the words are used ideally :)
> Document the Query module, especially specific queries

- integration_test/cases/browser/screenshot_test.exs
- lib/wallaby/browser.ex
I see that there was a some effort to [automatically name screenshots based on the module and test](https://github.com/keathley/wallaby/pull/156), but it's been quiet there for about 7 months.
This PR is simpler: just let users specify the filename, and default to a timestamp as we do now.
> Allow specifying a name for the screenshot file

- README.md
`only: [:test]` is important; otherwise staging or prod may blow up if phantomjs isn't installed
> Make deps examples consistent and test-only

- .travis.yml
After reviewing the builds, I realized that credo is not running in strict mode. You can see this in the following command output:
Analysis took 1.7 seconds (0.07s to load, 1.6s running checks)
520 mods/funs, found 1 software design suggestion.
Showing priority issues: ↑ ↗ →  (use `--strict` to show all issues,
`--help` for options).
Instead of `mix credo -- strict` it should be `mix credo --strict`.
> Run credo in strict mode

- lib/wallaby/experimental/chrome.ex
Arch Linux gives a different output when checking for the chromedriver version.
for example:
* On Arch
```
$ chromedriver --version
ChromeDriver 2.30
```
* On Mac:
```
$ chromedriver --version
ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)
```
So Arch misses the additional version hashes.
As these are not being used at all in the check for the version it should be safe to ignore that part.
> Support Arch Linux chromedriver

- config/test.exs
- lib/wallaby.ex
- lib/wallaby/driver/process_workspace.ex
- lib/wallaby/driver/process_workspace/server.ex
- lib/wallaby/driver/process_workspace/server_supervisor.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/phantom/server/server_state.ex
- lib/wallaby/phantom/server/start_task.ex
- priv/run_phantom.sh
- test/wallaby/driver/process_workspace_test.exs
- test/wallaby/phantom/server/server_state_test.exs
- test/wallaby/phantom/server_test.exs
PR commit contains several backend changes to solve the zombie phantom issue (#224).
1. New `ProcessWorkspace` helper which creates a temporary folder that is available for the life of the given process. This folder is a great place for writing the process wrapper script, creating local storage folders, etc. This folder is automatically deleted when the attached process exits (previously, these folders weren't getting cleaned up). Also, by writing the wrapper script to a temporary place on the file system instead of running it from priv, we are still able to use this library with an escript.
2. Improved run_phantom.sh wrapper script. This script now handles shutting down when STDIN is closed, shuts down when it receives an `INT`, `HUP`, or `TERM` signal, and shuts down when the underlying …
> Fixes zombie phantomjs

- .credo.exs
- integration_test/cases/browser/assert_refute_has_test.exs
- integration_test/cases/browser/assert_text_test.exs
- integration_test/cases/browser/cookies_test.exs
- integration_test/cases/browser/stale_nodes_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/element.ex
- lib/wallaby/exceptions.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/metadata.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
- test/wallaby/browser_test.exs
- test/wallaby/phantom/driver_test.exs
This normalizes exception names so they end in `Error`, per the Elixir style guide: https://github.com/lexmag/elixir-style-guide#exception-naming. It also enables the credo exception name check to ensure all new exceptions are named properly.
> Normalize exception names

- README.md
Wallaby doesn't need to started with other runtime dependencies since we encourage folks to start it explicitly in the test helper.
> Wallaby shouldn't be a runtime dependency

- priv/run_phantom.sh
After running wallaby as part of a separate application, I confirmed we were still leaving around zombie phantom processes (see #224). It turns out if we kill the script's process group, it will kill all of the child processes as well. This appears to fix the zombie issue once and for all.
One thing to note, I kill the process group by using the negative value of the wrapper script's pid, instead of using `ps axo pid, pgid` to look up the process group id. This is because I was occasionally running into issues where the process group lookup wasn't returning a result, causing
more zombie processes. Hopefully this approach won't cause any issues.
I've tested this on OS X and ubuntu and don't see any processes being left alive. I'm definitely not a shell scripting master, so any ideas for …
> Fixes zombie phantomjs processes

- .travis.yml
- integration_test/cases/browser/dialog_test.exs
- integration_test/chrome/all_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/driver.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- lib/wallaby/httpclient.ex
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/driver.ex
- lib/wallaby/query/error_message.ex
This PR does a few things. I would have normally broken this up but I wanted to get all of our chrome issues sorted at one time and I just got carried away. Here's the highlights:
* Fixes an issue with taking screenshots on chrome. Chrome doesn't support screenshots based on elements so we need to always screenshot using the session.
* Captured a specific chromedriver error for invalid selectors
* Fixes the dialog support for chrome. I'll discuss this in more detail below.
* Enable all of the tests for chrome.
In order to support dialogs and alerts in chrome I made the decision to remove `accept_dialogs` and `dismiss dialogs`. These were useful functions in phantom because phantom has no good way of managing dialog boxes. With chrome and selenium these functions are less useful since we …
> Finish chromedriver support.

- .travis.yml
- mix.exs
- mix.lock
As the title says, removes old elixir and erlang versions from our travis config.
> Remove old elixir releases from travis config

- integration_test/cases/browser/file_test.exs
Rather than a failed assertion reporting `Expected truthy, got false`,
it will instead output the values on the left and right hand side making
it easier to diagnose the problem. This isn't a big deal for these
specific tests, but will hopefully make life easier for anyone copying
them into their own project.
> Improves readability of file_test failures.

- lib/wallaby/httpclient.ex
- test/wallaby/http_client_test.exs
To make it a little easier to track down issues.
> Include HTTPoison errors in Wallaby error message when request fails.

- lib/wallaby/experimental/chrome/chromedriver.ex
Chromedriver has started throwing lots of warnings on the most recent version
of OSX. These warnings are harmless and we can't do anything about them. This
PR silences the warnings so that we reduce the noise.
> Silences warnings being thrown from chromedriver.

- lib/wallaby/httpclient.ex
This adds a jitter to any of our failed http requests. Using this should help
to avoid overwhelming the webdriver as well as avoid harmonic failures when lots
of requests fail at once. This should help to resolve issues #365 and #375.
> Add jitter to our http retries

- integration_test/cases/query_test.exs
- integration_test/support/pages/forms.html
- integration_test/support/pages/page_1.html
- lib/wallaby/query.ex
- lib/wallaby/query/error_message.ex
- lib/wallaby/query/xpath.ex
- test/wallaby/query/error_message_test.exs
Hi @keathley,
This PR will add two new features for the `Query` module. Now we are able to lookup HTML elements by:
- the `value` attribute (e.g. `Query.value("a-value")`)
- and for each `attribute-name` and `attribute-value` pair (e.q. `Query.attribute("an-attribute", "a-value")`)
Let me know what do you think! :rocket:
> Query.value and Query.attribute now available

- lib/wallaby/httpclient.ex
- test/wallaby/http_client_test.exs
- test/wallaby/phantom/server/server_state_test.exs
This will still throw the `MatchError`, but will carry the corresponding error message to the user instead of only `:obscure`.
Partially addresses #383 and #280.
> Return error message for obscure responses. Addresses #383 and #280

- lib/wallaby/experimental/selenium/webdriver_client.ex
- test/tools/start_webdriver.sh
- test/wallaby/experimental/selenium/webdriver_client_test.exs
We are seeing some failures on CI for `$WALLABY_SELENIUM_VERSION=3` and noticed that the Selenium and GeckoDriver versions were well behind, but Firefox was always set to latest. Hopefully updating them will allow them to cooperate with Firefox.
> Upgrade Selenium Server and GeckoDriver for CI

- mix.exs
A minor update to silence the compiler warning `found quoted keyword "coveralls" but the quotes are not required.` coming from a recent version of elixir
> silence quoted keyword warning from recent elixir versions

- README.md
Last night I realized that the documentation I had written for #390 was incorrect.
The README stated that you could set an option in application config,
but that was not the case. The correct way to configure the default
window size is to pass the option in to the Wallaby.start_session/1
function.
> Fix README documentation for configuring window size

- .travis.yml
- dialyzer.ignore_warnings
- lib/mix/tasks/safe_travis.ex
- mix.exs
Coveralls timing out is causing a lot of false positives on CI. This should recover from excoveralls failures.
Shamelessly ripped from [pinterest/elixir-thrift](https://github.com/pinterest/elixir-thrift/pull/389/files)
> Don't fail the build on Coveralls timeout

- integration_test/cases/inspect_test.exs
- lib/wallaby/element.ex
Addresses #266 
When passing a `Wallaby.Element` to `IO.inspect/2`, the elements outerHTML will be printed along with the normal representation of a struct, like so:
I would like some feedback on a few things:
- Where is the best place to define the `Inspect` implementation?
- Keep/change/throw out the coloring?
- Is the format alright?
- Should we request the `outerHTML` data when running inspect, or should the outerHTML be added to the `Wallaby.Element` struct itself?
Thanks!
cc/ @keathley @knewter @nathanl
> Print outerHTML when passing an Element to IO.inspect/2

- integration_test/cases/query_test.exs
- integration_test/support/pages/page_1.html
- lib/wallaby/query.ex
- lib/wallaby/query/xpath.ex
Addresses #344.
I wasn't able to find a way to escape the single quotes in the xpath expression, so I resorted to switching to double quotes as the delimiters.
Some places I found people saying you could escape them by doubling them, but that didn't seem to work.
Let me know what you think.
cc/ @keathley @mcasper
> Find elements by text that contain single quotes

- integration_test/cases/query_test.exs
- integration_test/support/pages/page_1.html
- lib/wallaby/query.ex
- test/wallaby/query/error_message_test.exs
This aims to address https://github.com/keathley/wallaby/issues/136
Description
===========
Adds `Query.data/3` to find an element by data-attribute. We make use of the existing `Query.attribute/3` function and simply pass prefix the `name` of the attribute with `data-`.
A couple of notes:
1. Decided for `Query.data` as opposed to something like `Query.data_attribute` but I'm happy to change that if you feel like it'd be more descriptive.
2. Named the first argument passed into `Query.data` as `name`, but I'm happy to change it to something else (like `key`) if that's preferred.
Also, I know it takes a lot to review PRs and maintain repos, so if this doesn't feel like the right way to go, don't worry about closing this. I was just trying to help out here since I've been using Wallaby more …
> Adds Query.data/3 to find by data-attribute

- integration_test/cases/query_test.exs
- integration_test/support/pages/forms.html
- lib/wallaby/browser.ex
- lib/wallaby/query.ex
- lib/wallaby/query/error_message.ex
- test/wallaby/query/error_message_test.exs
This is an attempt to handle https://github.com/keathley/wallaby/issues/380
Description
===========
Adds a `selected` condition to queries. This should only work with options, radio buttons, and checkboxes (since it uses `Element.selected?/1` underneath).
The usage is similar to the `visible` option for a query function: e.g. `Query.css("selector", selected: true)`. The default case, when neither `selected: true` nor `selected: false` is passed sets the condition to `:any`. In this way, if neither `true` nor `false` are specified, the query will return both selected and unselected elements. Having `true`, `false` or `:any` feels a bit unclean to me since now we have a boolean or a random atom `:any`, but I couldn't think of a better way to handle that. I'm happy to change that if there …
> Add selected condition to query

- README.md
For the user of the library, there is no default hackney config:
```
iex(1)> Application.ensure_all_started(:wallaby)
{:ok,
[:unicode_util_compat, :idna, :mimerl, :certifi, :ssl_verify_fun, :metrics,
:hackney, :httpoison, :poolboy, :poison, :wallaby]}
iex(2)> Application.get_env(:wallaby, :hackney_options, [])
[]
```
> Remove false comment about default hackney config

- integration_test/cases/query_test.exs
- lib/wallaby/query.ex
- test/wallaby/query_test.exs
Attempt to address #404 
Description
============
Adds functions `visible/2`, `selected/2`, `text/2`, `count/2`, and `at/2` for query options to compose queries.
```elixir
query =
Query.css(
".select-options",
visible: true,
selected: true,
text: "Select Option 2",
count: 1,
at: 0
)
query =
Query.css(".select-options")
|> Query.visible(true)
|> Query.selected(true)
|> Query.text("Select Option 2")
|> Query.count(1)
|> Query.at(0)
```
Note on `Query.text/2`
---------------------
We decided to go ahead an leave the two versions of `Query.text/2` for now, even though they perform different actions. One version creates a query of `method: :text` and the other adds the `text` condition to an existing query (see https://github.com/keathley/wallaby/issues/404#issuecomment-459343916 for more on …
> Add functions for query options

- lib/wallaby/browser.ex
- lib/wallaby/query.ex
- lib/wallaby/query/error_message.ex
There are situations where we might not care if the element is visible or not. Additionally, in some corner cases Safari 11 reports different visibility than other browsers. By adding a `visible: :any` option to Query we can support such situations, and optimize our tests to avoid checking visibility when it's not necessary.
> Add visible: :any option to Query

- lib/wallaby/session_store.ex
(for better browserstack handling)
When running tests on Browserstack on Chrome on Windows 10, the first test passes,
but when a second test starts, we get an error in Wallaby:
** (exit) exited in: GenServer.call(Wallaby.SessionStore, {:monitor, %Wallaby.Session{driver: Wallaby.Experimental.Selenium, id: "session_id", screenshots: [], server: :none, session_url: "http://login:password@hub.browserstack.com:80/wd/hub/session/session_id", url: "http://login:password@hub.browserstack.com:80/wd/hub/session/session_id"}}, 5000)
** (EXIT) time out
Increasing this timeout to 10s seems to resolve this particular issue.
> Increase SessionStore.monitor genserver timeout

- lib/wallaby/httpclient.ex
Edge 17 responds with: "Stale element..." (uppercase S)
Safari 11 responds with: "An element command failed..."
> Handle Safari 11 and Edge 17 stale reference error

- integration_test/chrome/all_test.exs
- integration_test/phantom/all_test.exs
- integration_test/tests.exs
- lib/wallaby/experimental/selenium.ex
Similarily to #428, `take_screenshot` was handled by Chromedriver and PhantomJS, but for Selenium functions was not implemented. The comment said
> Screenshots don't appear to be supported with Gecko Driver
but screenshots are working just fine using recent Geckodriver.
Since screenshot tests should be now passing on all platforms, `integration_test/cases/browser/screenshot_test.exs` was moved to the set of default tests for all drivers.
> Add support for taking screenshot in Selenium

- integration_test/chrome/all_test.exs
- integration_test/phantom/all_test.exs
- integration_test/tests.exs
- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
JS window.alert, window.confirm and window.prompt were handled by Chromedriver and PhantomJS, but for Selenium functions for accept and dismiss them were not implemented.
This PR adds code that allows to use the following functions:
accept_alert/2,
accept_confirm/2,
accept_prompt/2,
accept_prompt/3,
dismiss_confirm/2
dismiss_prompt/2,
dismiss_alert/2.
To make it work with Firefox as well as Chrome, the `dismiss_prompt/2` endpoint was switched to the one specified by Selenium WebDriver JSON Wire Protocol (instead of the endpoint specified in the W3C WebDriver specification), which is the same as dismiss_confirm/2. This change also affects the Chromedriver backend (since it uses the same WebDriver module as Selenium) but should not cause any regressions.
Since all dialog tests should be now …
> Add support for handling JS confirm, alert and prompt in Selenium

- integration_test/support/session_case.ex
Chrome tests are being run in headless mode, so I think we can do that for selenium as well. This is less annoying when using selenium-standalone jar and locally installed firefox, because newly opened windows were stealing system focus.
> Run selenium tests in headless mode in Firefox

- integration_test/support/session_case.ex
- lib/wallaby.ex
- lib/wallaby/phantom.ex
See https://github.com/keathley/wallaby/blob/master/lib/wallaby.ex#L80
While I agree that the `:driver` option could be useful, currently it's not implemented.
> Fix Wallaby.start_session_opts type spec - passing :driver doesn't do anyting

- integration_test/chrome/all_test.exs
- integration_test/selenium/all_test.exs
@mhanberg Tests weren't added to  Chrome and Selenium lists for tests to run
> Enable running hover integration tests added in #435

- .tool-versions
- .travis.yml
- dialyzer.ignore_warnings
- test/tools/start_webdriver.sh
This would be 5 * 3 * 3 = 45 jobs to run so I'm not sure if it's a good idea. Maybe we could reduce the amount of jobs to run for one version combo?
edit: Dropped selenium 2, dropped elixir 1.7 and otp 20, also excluded elixir 1.8+otp22 and elixir 1.9+otp21 to simplify the matrix. Now it's 2x4, looks good but I need to fix the dialyzer warning
> Update and add new elixir and erlang versions used for testing on travis

- integration_test/cases/browser/window_handles_test.exs
- integration_test/cases/browser/window_position_test.exs
- integration_test/cases/browser/window_size_test.exs
- integration_test/chrome/all_test.exs
- integration_test/selenium/all_test.exs
- integration_test/support/pages/windows.html
- lib/wallaby/browser.ex
- lib/wallaby/driver.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- lib/wallaby/phantom.ex
- test/wallaby/experimental/selenium/webdriver_client_test.exs
Closes #360
TODO:
- ~~Revisit handling errors, reading the value from the response and return types (`:ok` is just the happy path)~~ that's fine for now I think
For the unaware: I'm following the [Selenium WebDriver Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol). The [W3C WebDriver Protocol](https://w3c.github.io/webdriver/#endpoints) has too many changes to try to support both of them at the same time. We will need to have a separate WebdriverClient module for it for people that want to test in Safari 12 or newer, Edge 18 or newer, new Appium versions etc.
> Interacting with opened windows

- integration_test/cases/browser/frames_test.exs
- integration_test/support/pages/frames.html
- lib/wallaby/browser.ex
- lib/wallaby/driver.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- lib/wallaby/phantom.ex
- test/wallaby/experimental/selenium/webdriver_client_test.exs
This is a key feature differentiating Selenium/WebDriver from some other automation frameworks like Cypress - Selenium allows switching to frames with different origin while Cypress does not. This is helpful e.g. when testing payments.
To do:
edit: What I found is that switching by name/ID is not supported in most WebDrivers. Since switching by WebElement seems to be working fine, I left only Query as a possible argument, but kept all options in the `WebdriverClient` module - this is a private module but if someone really needs switching by index, they'll find it there.
edit: I extracted this to a separate function but in the Browser module only.
> Switching between frames

- README.md
According to the changelog they were removed in 0.21.
> Remove refernces to accept/dismiss_dialogs

- mix.exs
closes #451 
Looks like hex publish uses [`Build.prepare_package()`](https://github.com/hexpm/hex/blob/3c26cf1ae147a45d109f70069591e5df711728b3/lib/mix/tasks/hex.publish.ex#L117) which does [`meta_for`](https://github.com/hexpm/hex/blob/ab402f98c1efe6855c93dfc5130c2b7a4b1ef753/lib/mix/tasks/hex.build.ex#L141) which does [`package`](https://github.com/hexpm/hex/blob/ab402f98c1efe6855c93dfc5130c2b7a4b1ef753/lib/mix/tasks/hex.build.ex#L206) where files are filtered by [`exclude_patterns`](https://github.com/hexpm/hex/blob/ab402f98c1efe6855c93dfc5130c2b7a4b1ef753/lib/mix/tasks/hex.build.ex#L275)
So we should be able to use `exclude_patterns`, not sure why it's not documented in docs for publish but it's probably because of incomplete docs, I'm pretty sure this will work.
> Don't ship coveralls task in hex package

- lib/wallaby.ex
- lib/wallaby/httpclient.ex
Hopefully this resolves/helps #365 
I have tested this locally with hundreds to thousands of tests running in parallel, and the only reason I've seen it fall apart is because of my computer running out of open file handles.
> Tune Hackney to not overload WebDrivers

- .credo.exs
- .travis.yml
- CHANGELOG.md
- README.md
- integration_test/chrome/all_test.exs
- integration_test/chrome/capabilities_test.exs
- integration_test/selenium/all_test.exs
- integration_test/selenium/capabilities_test.exs
- integration_test/support/session_case.ex
- lib/wallaby/experimental/chrome.ex
- lib/wallaby/experimental/selenium.ex
- lib/wallaby/experimental/selenium/webdriver_client.ex
- lib/wallaby/httpclient.ex
- test/tools/start_webdriver.sh
- test/wallaby/http_client_test.exs
- Enables the ability to set capabilities by passing them as an option and using application configuration.
- Implements default capabilities for Selenium.
- Moves configuration options for using chrome headlessly, the chrome binary, and the chromedriver binary to the `:chromedriver` key in the `:wallaby` application config.
- Moves documentation for Chrome and Selenium from the README and into their respective moduledocs.
- Raise when we receive a generic error from the driver
- Disables a few credo rules that I don't think are valuable: ParenthesesOnZeroArtiyDefs conflicts with the formatter and PipeChainStart is not useful as a code quality metric
cc/ @michallepicki 
Resolves #460
> Enhance and standardize capabilities between drivers

- README.md
Following on from a discussion in the elixir slack, update mentions of Ecto 2 to indicate support for Ecto 3 as well.
> Update Ecto 2 reference to indicate 2 or 3

- .github/workflows/inch.yml
Apparently it is broken past that release...
https://github.com/rrrene/inch_ex/issues/60
> Run Inch with elixir 1.7

- .github/workflows/ci.yml
The new Github actions based workflow is great! ❤️  🎉 
Just a couple adjustments...
1. Changed the script to build on all pushes and PRs. I found I needed this change when I was pushing code to a branch on my own fork and it wasn't doing anything.
2. Disabled `fail_fast`. Without this, if one job in the matrix fails, it cancels the rest of them. However, when the rest of the jobs are cancelled, we can't see the test results for the other elixir versions.
> CI adjustments

- lib/wallaby/phantom/server.ex
Since we've migrated to Github actions, I've been getting intermittent test run failures saying there was a timeout starting the phantomjs servers
06:11:00.723 [info]  Application wallaby exited: Wallaby.start(:normal, []) returned an error: shutdown: failed to start child: Wallaby.Phantom
** (EXIT) shutdown: failed to start child: Wallaby.ServerPool
** (EXIT) an exception was raised:
** (MatchError) no match of right hand side value: {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.2485.0>, pid: #PID<0.2487.0>, ref: #Reference<0.1308822412.2435317761.47248>}, 5000]}}}
(poolboy) src/poolboy.erl:275: :poolboy.new_worker/1
(poolboy) src/poolboy.erl:296: :poolboy.prepopulate/3
(poolboy) src/poolboy.erl:145: :poolboy.init/3
(stdlib) gen_server.erl:374: :gen_server.init_it/2
(stdlib) …
> Increase timeout for starting phantomjs servers

- lib/wallaby/httpclient.ex
- lib/wallaby/phantom/driver.ex
I wasn't sure the type of the `locator` param on this function, so I tracked it down and added a typespec. This matches the typespec in `Wallaby.Experimental.Selenium.WebdriverClient`:
https://github.com/elixir-wallaby/wallaby/blob/486e758d77c502884df949eee007aa085d848fad/lib/wallaby/experimental/selenium/webdriver_client.ex#L37-L47
I didn't end up adding the `{:error, _}` return because I'm still tracking down the possible error returns for these functions, and we haven't documented the error returns anywhere else in our API clients. I'm thinking I'd like to figure that out and submit that in a future PR.
> Add typespec for Phantom.Driver.find_elements/2

- test/wallaby/experimental/selenium/webdriver_client_test.exs
- test/wallaby/phantom/driver_test.exs
This upgrades the bypass expectations to use the new [`expect/4`](http://hexdocs.pm/bypass/1.0.0/Bypass.html#expect/4) function, which allows for multiple expectations per test. This removes the need for work-arounds like `stub_backend` and allows expecting that both the primary endpoint and log endpoint are called in a single test.
> Upgrade bypass expectations

- test/support/http_client_case.ex
- test/wallaby/experimental/selenium/webdriver_client_test.exs
- test/wallaby/http_client_test.exs
- test/wallaby/phantom/driver_test.exs
This adds json encoding logic to `send_json_resp/3` so we don't have to manually encode the response body. This allows responses to go from being written as a JSON string
```elixir
send_json_resp(conn, 200, ~s<{
"sessionId": "#{new_session_id}",
"status": 0,
"value": {
"acceptSslCerts": false,
"browserName": "phantomjs"
}
}>)
```
to be able to use an Elixir map
```elixir
send_json_resp(conn, 200, %{
"sessionId" => new_session_id,
"status" => 0,
"value" => %{
"acceptSslCerts" => false,
"browserName" => "phantomjs"
}
})
```
This improvement has a few benefits:
* We don't have to write raw JSON in tests (or send a data structure through `Jason.encode!/1`)
* The formatter will take care of spacing
* Assertions may be come easier when comparing the map used for the server response to the …
> Tests: Allow send_json_resp/3 to encode map as json

- .github/workflows/ci.yml
This adds two additional checks to the build.
1. Fails the build if there's compilation warnings (within wallaby, not dependencies)
2. Ensures code does not need formatting.
Since there's some differences in formatting between Elixir 1.7.x and 1.9.x, this only runs the formatting check on Elixir 1.9.x.
> Add additional build checks

- mix.exs
This makes it so we can run `mix docs` instead of `MIX_ENV=docs mix docs`.
> Automatically run mix docs with MIX_ENV=docs

- lib/wallaby/experimental/selenium.ex
The `:create_session_fn` and `:end_session_fn` options were only for testing and are no longer needed since we've since migrated to bypass-based tests (#504) .
> Remove function injection in Selenium driver

- test/wallaby/browser_test.exs
Occasionally the test suite will fail like this
1) test visit/2 relative path with leading slash, base url no trailing slash (Wallaby.BrowserTest)
test/wallaby/browser_test.exs:56
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.4095.0>}}
stacktrace:
test/wallaby/browser_test.exs:43: Wallaby.BrowserTest.__ex_unit_setup_0/1
test/wallaby/browser_test.exs:1: Wallaby.BrowserTest.__ex_unit__/2
https://github.com/aaronrenner/wallaby/runs/409174774#step:6:70
This appears to be because the named TestDriver process doesn't always finish shutting down before the next setup block runs. By using `start_supervised!/1`, this PR links the TestSupervisor instance to the test supervisor, which ensures shutdown occurs before the next test is started.
> Fixes TestDriver already_started test failures

- integration_test/chrome/capabilities_test.exs
- integration_test/chrome/starting_sessions_test.exs
- integration_test/phantom/starting_sessions_test.exs
- test/support/application_control.ex
- test/support/chrome/chrome_test_script.ex
- test/support/phantom/phantom_test_script.ex
- test/support/test_script_utils.ex
- test/support/test_workspace.ex
This adds integration tests for around starting wallaby and the underlying phantomjs and chromedriver processes. These tests establish a pattern of how to test a webdriver server's startup and will make it easier to work on the following issues:
* #509 - need ability to pass custom options to chromedriver
* #423 - wallaby crashes on startup when phantomjs pool takes too long to start.
I chose to test this via integration tests because I'm thinking this style of test will give us the most flexibility to address #423 while having test coverage to ensure wallaby as a whole continues to function as users expect.
> Add integration tests for starting phantom and chromedriver

- lib/wallaby/phantom.ex
- lib/wallaby/phantom/server_pool.ex
This encapsulates phantom's poolboy related logic into its own module. This moves the checkin/checkout logic into its own module and allows the pool to be started with Elixir 1.7+ style supervisor specs. The only operational difference is the pool name has gone from `Wallaby.ServerPool` to  `Wallaby.Phantom.ServerPool`.
> Extract poolboy logic into Wallaby.Phantom.ServerPool

- integration_test/phantom/starting_sessions_test.exs
- lib/wallaby/phantom.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/phantom/server_pool.ex
- test/support/phantom/phantom_test_script.ex
- test/support/test_script_utils.ex
- test/support/test_workspace.ex
This fixes a couple issues:
1. If the user configures their app like this:
```elixir
config :wallaby, phantomjs: "wrong-path"
```
and a `phantomjs` executable is in the path, wallaby will ignore the incorrect configuration and use the `phantomjs` executable on the path instead. This behavior is surprising and could lead to a user accidentally using the wrong version of phantomjs. It also makes the `Driver.validate` callback difficult to test if phantomjs is installed.
2. If the user configures wallaby to reference an install in their home directory, 
```elixir
config :wallaby, phantomjs: "~/Downloads/phantomjs"
```
the `validate` callback succeeds, but the workers in the server pool fail to start because the server pool gets its phantomjs path a different way. This PR now passes phantomjs …
> Fix issues with phantomjs path handling

- integration_test/phantom/starting_sessions_test.exs
- lib/wallaby.ex
- lib/wallaby/phantom/server.ex
- lib/wallaby/phantom/server/server_state.ex
- lib/wallaby/phantom/server_pool.ex
- test/wallaby/phantom/server/server_state_test.exs
- test/wallaby/phantom/server_test.exs
Follow up to #514.
This removes `Wallaby.phantomjs_path/0` in favor of `Wallaby.Phantom.find_phantomjs_executable/0`. This important because `Wallaby.phantomjs_path` does not do the same checking and path expansion as `Wallaby.Phantom.find_phantomjs_executeable`.
Since `phantomjs_path` is always going to be passed as an option from `ServerPool.child_spec/1`, I moved it from a keyword argument to a positional argument on `Server.start_link/1`. This provides a couple of benefits:
1. It's more clear when calling `Server.start_link/1` the `phantomjs_path` is required.
2. We can remove the fallback logic that was calling `Wallaby.phantomjs_path/0` and the tests that manipulated the application environment.
I have another PR after this where I'd like to pass `phantomjs_args` in a similar …
> Remove Wallaby.phantomjs_path/0

- integration_test/chrome/starting_sessions_test.exs
- lib/wallaby/exceptions.ex
- lib/wallaby/experimental/chrome.ex
- test/support/chrome/chrome_test_script.ex
This is similar to #514 but for chromedriver. This ensures that an incorrectly configured chromedriver path does not silently fall back to a chromedriver instance in the system `PATH`.
> Fix issue where chromedriver starts on incorrect path

- integration_test/cases/browser/screenshot_test.exs
- integration_test/chrome/starting_sessions_test.exs
- integration_test/phantom/starting_sessions_test.exs
- lib/wallaby/browser.ex
- test/support/test_workspace.ex
When wallaby takes a screenshot (either automatically or with `log: true`) it currently outputs a url like this:
```
Screenshot taken, find it at file:////home/aaron/projects/wallaby_liveview_playground/screenshots/1584041849570197413_users_have_names_in_LiveView(1).png
```
This url has an extra slash (`file:////` instead of `file:///`) which is invalid and makes it so it's not clickable in the terminal.
This PR fixes the invalid screenshot urls and adds tests for when  `screenshot_dir` is configured with the following types of directories:
* Absolute paths
* Relative paths
* Home directory based paths
* Paths with spaces in them
The majority of this PR is updates to the screenshots test suite. Here are a few high-level changes to the tests
1. Ensure the various types of directories that …
> Fix screenshot file url output

- README.md
- mix.exs
I noticed that there were some incorrect links, as well as the pubished
docs not looking correct. The experimental driver module docs are not
showing up on the hexdocs
Ex: https://hexdocs.pm/wallaby/Wallaby.Experimental.Selenium.html#content
I will re-publish the docs after this is merged.
> Fix some documentation

- CHANGELOG.md
- README.md
- integration_test/chrome/capabilities_test.exs
- integration_test/chrome/starting_sessions_test.exs
- lib/wallaby.ex
- lib/wallaby/chrome.ex
- lib/wallaby/chrome/chromedriver.ex
- lib/wallaby/chrome/chromedriver/readiness_checker.ex
- lib/wallaby/chrome/chromedriver/server.ex
- lib/wallaby/chrome/logger.ex
- lib/wallaby/phantom.ex
- lib/wallaby/selenium.ex
- lib/wallaby/session_store.ex
- lib/wallaby/webdriver_client.ex
- test/wallaby/chrome/chromedriver/server_test.exs
- test/wallaby/chrome/logger_test.exs
- test/wallaby/selenium/start_session_config_test.exs
- test/wallaby/selenium/webdriver_client_test.exs
- test/wallaby/selenium_test.exs
- Warns on use of `Wallaby.Phantom`
- Documents `Wallaby.Phantom` as deprecated
- Makes `Wallaby.Chrome` the default driver
- Removes references to phantomjs in the README
Partially addresses #437 
Resolves #196 
Resolves #164
> Deprecate PhantomJS

- lib/wallaby/driver/process_workspace/server.ex
- lib/wallaby/driver/process_workspace/server_supervisor.ex
- test/wallaby/driver/process_workspace_test.exs
Also removes call to `Process.sleep` in the test in favor of recursion with a timeout.
I was investigating some flaky tests that involved the `assert File.exists?(workspace_path)` lines in the tests, and noticed that was a `:simple_one_for_one` supervisor. Converting it to a `DynamicSupervisor` seems to have fixed flakiness.
The call to `Process.sleep` was not part of the flakiness, but I converted it to use recursion with a timeout instead. Let me know what you think about that.
> Update ServerSupervisor to be a DynamicSupervisor

- CHANGELOG.md
- lib/wallaby/browser.ex
Fixes #539.
Changes Wallaby.Browser.sync_result from `@opaque` to `@type`.
> Change Wallaby.Browser.sync_result from opaque to type

- test/support/utils.ex
- test/wallaby/chrome/chromedriver/server_test.exs
- test/wallaby/driver/process_workspace_test.exs
These tests were flakey on CI, hopefully this helps with that.
> Wrap server_test assertions in timeout helper function

- lib/wallaby/query.ex
Fixes #542 
I narrowed this down to `Query.compile(@query_from_module_attribute)`. Looks like with the query created at compile time, dialyzer has more information to find discrepancies. Types in the query module were missing some possible values - I updated them to be slightly more general and cover more of valid queries. This fixes the reported bugs but there still could be more valid query structs that are not covered by the current types, so we might need to revisit this in the future.
> Fix Query type specifications

- lib/wallaby/session_store.ex
- test/wallaby/session_store_test.exs
ETS records weren't being correctly removed from `SessionStore`, leaving stale sessions around in `SessionStore.list_sessions_for`. By returning the `pid` from the `:ets.select`, we can ensure a correct match & delete of the session.
Could be useful to add a `defdelegate active_sessions` in the main `Wallaby` interface that calls `SessionStore.list_sessions_for`, but didn't want to make that assumption in this PR.
Fixes the issue pointed out in #550
> Ensure sessions are correctly deleted from ETS by passing the pid along

- lib/wallaby/browser.ex
Found this small typo in the docs.
> Fix for typo in fill_in docs

- lib/wallaby/browser.ex
When using `Wallaby.Browser.has_text?/2`  and `Wallaby.Browser.assert_text/2` in a codebase, dialyzer throws warnings when you call these funcs with a `Wallaby.Session`, even though it is supported. Update the `@spec` declarations to use `parent` instead of `Element.t()`, so dialyzer can properly determine the usage is valid.
Additionally, in `Wallaby.Browser`, there is a `@type locator :: String.t()` def, which is only used 3x in the module, whereas `String.t()` is used 33x, sometimes in sibling `@spec` statements for the same multi-head function. Dropped `locator` and made the 3 instances `String.t()` instead.
> Fix typespec issues

- .dialyzer_ignore.exs
- .github/workflows/chromedriver.yml
- .github/workflows/inch.yml
- .github/workflows/linting.yml
- .github/workflows/selenium.yml
- .github/workflows/unit_tests.yml
- CHANGELOG.md
- README.md
- integration_test/chrome/starting_sessions_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/chrome.ex
- lib/wallaby/selenium.ex
- lib/wallaby/session_store.ex
- mix.exs
- test/support/test_workspace.ex
Ensure all sessions are closed on exit
If you were running a test with many sessions, and it was either the last test to run or the only test to run, then there was the chance that the SessionStore would exit before we could ask the webdriver to close the sessions.
While the webdriver would successfully die, this would leave zombie browser processes lingering, tormenting the living.
Here, we use the after_suite callback from ExUnit to ensure that these sessions get closed before ExUnit kills Wallaby.
Unfortunately this was introduced in Elixir 1.8, so we now have to raise the minimum Elixir version to 1.8, which I think is reasonable, considering the latest version is 1.11.
Fixes #554 
Fixes #544
> Ensure all sessions are closed after test suite finished.

- CHANGELOG.md
- integration_test/cases/browser/assert_text_test.exs
- lib/wallaby/browser.ex
This patch changes the `assert_text\2` and the `assert_text\3` methods to return the parent rather than `true` if the assertion passes.
This will allow easy piping of the method.
Closes https://github.com/elixir-wallaby/wallaby/issues/561
> Make assert_text pipeable

- lib/wallaby/browser.ex
- lib/wallaby/helpers/key_codes.ex
- lib/wallaby/selenium.ex
- lib/wallaby/webdriver_client.ex
- test/wallaby/helpers/key_codes_test.exs
Currently, Wallaby's `Browser.attach_file` uses `set_value` to set a file path as the value of an file input.
Unfortunately, this does not actually attach a file when using Selenium, and submitting a form when using this function results in errors for invalid multipart payloads. This problem is more pronounced when using a remote Selenium instance, as a file input can only attach a file that is available on the local machine.
Selenium's standalone server provides a means of handling this that is implemented in other libraries (e.g., [the official Python implementation](https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/py/selenium/webdriver/remote/webelement.py#L511)).
The basic outline of how this is supposed to work with Selenium servers is as follows: …
> Fix Selenium uploads

- lib/wallaby/chrome.ex
Setting the `chromedriver` outside the projects doesn't work even if I follow the docs.
```elixir
** (Mix) Could not start application wallaby: exited in: Wallaby.start(:normal, [])
** (EXIT) an exception was raised:
** (FunctionClauseError) no function clause matching in Keyword.get/3
(elixir 1.10.4) lib/keyword.ex:201: Keyword.get("/media/alexandrubagu/devel/utils/chromedriver", :path, "chromedriver")
(wallaby 0.28.0) lib/wallaby/chrome.ex:174: Wallaby.Chrome.find_chromedriver_executable/0
(wallaby 0.28.0) lib/wallaby/chrome.ex:157: Wallaby.Chrome.validate/0
(wallaby 0.28.0) lib/wallaby.ex:31: Wallaby.start/2
```
Solution: 
- change: ```config :wallaby, chromedriver: "/media/alexandrubagu/devel/utils/chromedriver"```
- to: ```config :wallaby, :chromedriver, path: …
```
> fixes the DependencyError message  in chrome.ex

- README.md
To provide example configuration when an application has additional
resources (above just the SQL database) that should be shared between
processes.
See https://github.com/elixir-wallaby/wallaby/discussions/591
> README.md: Improve instructions about async tests with Phoenix

- .tool-versions
- integration_test/selenium/selenium_capabilities_test.exs
- lib/wallaby/selenium.ex
- test/wallaby/selenium/start_session_config_test.exs
This enables async tests while using the default selenium configuration.
> Put metadata into useragent for Firefox

- integration_test/cases/browser/assert_css_test.exs
- lib/wallaby/browser.ex
@adkron posted an issue: https://github.com/elixir-wallaby/wallaby/issues/585 that the `has_css?/2` function was raising an exception.
This is my first PR in the project, and I'm new to open source 🙏 Please let me know if I'm breaking any rules or need to adjust anything!
the `has_css?/2` method was using `find/1` instead of `has?/1` causing it to throw an error instead of returning a boolean.
I've added testing and made test names consistent for has_css?/2, has_css/3, has_no_css?/2, and has_no_css/3 to make sure all work as expected.
> has_css? should return a boolean. Fix for Issue: #585.

- lib/wallaby/browser.ex
- lib/wallaby/helpers/key_codes.ex
- lib/wallaby/session.ex
> Expand documentation for window related functions

- CHANGELOG.md
- lib/wallaby/query.ex
- lib/wallaby/query/error_message.ex
- test/wallaby/query_test.exs
This is achieved with a lazy default for `conditions[:count]`.
The function `Query.count/1` must now be used to get the effective count condition.
Alternative would have been to continue setting `count` to a
non `nil` default when conditions are first built. This has the inconvenient
of not being to distinguish a count set by default from an explicit one (i.e.
`Query.css(".x") |> Query.at(0)` from `Query.css(".x", count: 1) |> Query.at(0)`)
[Fixes #641]
To avoid conflicts, this includes #636 and #638
> Remove default for `count` when given an `at` option.

- integration_test/cases/browser/assert_refute_has_test.exs
- integration_test/cases/query_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/query.ex
- lib/wallaby/query/error_message.ex
- test/wallaby/query/error_message_test.exs
1) `assert_has` gave an unexcepted error.
2) `find` gave a wrong error messages always indicating a 0 found count:
"The element at index X is not available because 0 elements..."
This PR provides a more instructive error message for failures. It also
distinguishes between invalid values for `at` and values that are not found.
> Fix failures related to `at` queries.

- README.md
Esbuild has become the new standard for Phoenix asset management, and so this adds a note about how to use Wallaby with it.
> Adds esbuild config info to the README

- README.md
Part 1 of 2 related bits to ensure you can run your tests in async mode with Wallaby for LiveView, you need the user_agent (at least based on my testing). The other part is in another PR adding the SQL sandbox to the mount.
> Adds user_agent to endpoint.ex in the README

- README.md
Low friction point, but can stop folks from getting started as easily as they could if they don't realize this doesn't bundle the binaries.
> Add driver install notes to README

- integration_test/cases/browser/assert_refute_has_test.exs
- integration_test/cases/browser/window_position_test.exs
- integration_test/chrome/starting_sessions_test.exs
- lib/wallaby/chrome.ex
- test/support/chrome/chrome_test_script.ex
- test/wallaby/chrome/chromedriver/server_test.exs
I wasn't able to push changes to #684, so just creating this to let the tests run
- Fixes #685 When google chrome and chromedriver versions are out of sync wallaby can start in a bad state. We added a version comparison step to `Wallaby.Chrome.validate/0` that will error during application start if chrome and chrome versions do not match to a major, minor, and build version.
- Use correct config option in DependencyError
> add check for chromedriver chrome version match

- lib/wallaby/chrome.ex
We weren't accounting for Chromium when checking the versions of Chrome and ChromeDriver were matching.
@michallepicki can you install this branch and see if it fixes the problem? I was able to confirm that it works with Chromium locally on my MacBook, but haven't tested it manually for Chromium on Linux.
Thanks
Fixes #697 (maybe)
> fix(chromedriver): Account for Chromium when doing the version matching

- integration_test/cases/browser/cookies_test.exs
- lib/wallaby/browser.ex
- lib/wallaby/chrome.ex
- lib/wallaby/driver.ex
- lib/wallaby/exceptions.ex
- lib/wallaby/selenium.ex
- lib/wallaby/webdriver_client.ex
- test/wallaby/selenium/webdriver_client_test.exs
This PR adds a `set_cookie/4` function to permit the setting of optional cookie attributes per the [WebDriver specification](https://www.w3.org/TR/webdriver1/#cookies).
I have a project that needs to be able to set more than just `name` and `value` of a cookie; namely `Domain`, `Secure`, and `HttpOnly`.
> FEATURE: Allow setting of optional cookie attributes

- lib/wallaby/query/error_message.ex
- test/wallaby/query/error_message_test.exs
This pull request surfaces the `text` condition value when it's specified in CSS queries, and leaves the existing error message as-is when the condition _isn't_ specified.
I frequently build out css queries using the `text` condition (in combination with the base css selector of the query). Sometimes I would get failures where the element selector was found in the application UI but failed due the `text` condition, but in those cases the error message would only reference the selector, which would lead me to think that the element hadn't been present at all. 
These cases usually led me to open the screenshots and see the element present in the UI and realize my error—usually a case mismatch or outright typo🤦🏻‍♂️—and it's happened to me enough that I figured the lib could and should …
> Surface 'text' condition in css query error message when specified

- README.md
- `assign_new/3` was one of several functions moved to `Phoenix.Component` in the phoenix_live_view 0.18.0 release
- we still need the `import Phoenix.LiveView` due to other funcs called in the `AllowEctoSandbox` module
> Update README's AllowEctoSandbox config for liveview 0.18.X

- lib/wallaby/chrome.ex
- lib/wallaby/feature.ex
This makes it possible to override `headless` and `binary` for a particular test, e.g., 
```elixir
@sessions [[headless: false]]
feature "my feature", %{session: session} do 
...
end
```
> Chrome headless and binary opts can be passed in @sessions

- integration_test/chrome/capabilities_test.exs
- lib/wallaby/chrome.ex
> Use detected chrome path as default

- lib/wallaby/element.ex
Hi, found a minor bug, spec for function size is wrong.
Thanks!
> Fix Wallaby.Element.size/1 spec

- README.md
A warning is issued for use of `get_env/2` used outside of a module. The warning suggests using `compile_env/3` instead.
This change updates the documentation to conform to this suggestion and remove the warning, resulting in a cleaner and more modern setup for `wallaby`.
Resolves [#761](https://github.com/elixir-wallaby/wallaby/issues/761)
> Update README to Avoid Elixir Warning

- README.md
The test environment is unable to read an `.ex` file located in the `config/` dir by default for Phoenix apps as of v1.7
This change makes a small edit to the README to suggest the `sandbox.ex` file be placed in the `test/support` dir.
> Update README: Local Sandbox File Location

- lib/wallaby/query.ex
This beefs up the docs on `Query.text/2`, which a lot of examples combine with `assert_has/2` for asserting that a particular element has some text. Pointing to `assert_text/{2,3}` from the docs here would have resolved a recent issue Mitch kindly helped me with [in Slack](https://elixir-lang.slack.com/archives/C4H1XRC0J/p1715093283885629) where I was trying to assert on the text of multiple nested elements.
> Make Query.text/2 docs also point to assert_text/{2,3}

- README.md
This change separates the setup steps to use Wallaby with Phoenix from the specific steps needed to use with Phoenix + Ecto. This makes setup a bit clearer for the case when using Phoenix without Ecto or a database.
> Update README: Separate Phoenix setup from Ecto

- lib/wallaby/feature.ex
- `ExUnit.Case.register_test/6` has been available since Elixir 1.11.0, and now triggers deprecation warnings as of Elixir 1.17. This would be a breaking change if the intention is to support Elixir versions prior to 1.11, but I think we're all good on that front, given the existing CI version matrix
> Address deprecation; prefer ExUnit.Case.register_test/6

- lib/wallaby/httpclient.ex
Hi Mitch! When upgrading from 0.30.6 to 0.30.7, I started seeing a crash in `Wallaby.HTTPClient.check_for_response_errors/1` during JSON decode when an unexpected alert is opened. The message coming back from Chromedriver looks like this:
```elixir
%{
"sessionId" => "ff16e3040b4a88c33e77c4af572cddd9",
"status" => 26,
"value" => %{
"message" => "unexpected alert open: {Alert text : Error loading data, please refresh and try again}\n  (Session info: chrome-headless-shell=125.0.6422.142)\n  (Driver info: chromedriver=125.0.6422.78 (14db42ec38aded3304a3e624a0a038e02956b87e-refs/branch-heads/6422@{#1088}),platform=Mac OS X 14.5.0 x86_64)"
}
}
```
The error in the test runner looks like this:
```
1) feature blah blah blah
test/my_app_web/e2e/my_test.exs:90
** (Jason.DecodeError) unexpected byte …
```
> Improve crash decoding malformed JSON from Chromedriver

- lib/wallaby/httpclient.ex
This is an improvement over #778. By falling back to the full message value from Chromedriver, we can correctly get the `:unexpected_alert` condition to match on the bizarre, not-quite-JSON message from Chromedriver like:
```
"message" => "unexpected alert open: {Alert text : Error loading data, please refresh and try again}\n  (Session info: chrome-headless-shell=125.0.6422.142)\n  (Driver info: chromedriver=125.0.6422.78 (14db42ec38aded3304a3e624a0a038e02956b87e-refs/branch-heads/6422@{#1088}),platform=Mac OS X 14.5.0 x86_64)"
```
Applying this patch to my local copy, my default-configured Chromedriver correctly ignores the alert and my tests that passed on v0.36.6 again pass.
> Fix unhandled alerts not being properly ignored

- .github/workflows/ci.yml
- integration_test/cases/feature/use_feature_test.exs
- lib/wallaby/feature.ex
This fixes an unintended behavior where having `use Wallaby.Feature` at the top of your module would cause a browser to be spawned for every test in the module, not just `feature` tests. The result is that if you had a large test module, most of which used the normal `test` macro and one of which used the `feature` macro, every test would take a minimum of a third of a second or more.
~I also took the liberty to check and see in the `setup` block if we already had a `:session`, and if so, avoid spawning a second. I don't *think* anyone was relying on the behavior where a second browser was being spawned if you had `use Wallaby.Feature` at both the top of the module and a `describe` block.~
Resolves #794
> Only spawn a browser when using the `feature` macro, not normal `test`s

- README.md
I spent a while trying to understand how to enable WebAuthn Virtual Authenticator when testing with Wallaby. [Others have wanted to do this before](https://github.com/elixir-wallaby/wallaby/discussions/700) but it seems not documented anywhere. I thought it's worth having a short section in the readme file.
Please accept my apologies for being a noob at open source. I'm happy to take direction to further refine things.
> Docs for enabling Virtual Authenticator in Chromedriver

- README.md
💁 This change updates the configuration example for umbrella apps using Elixir >= 1.14. Calling `Application.get_env/3` and friends in the module body was [hard deprecated in Elixir 1.14.0](https://github.com/elixir-lang/elixir/blob/v1.14/CHANGELOG.md#4-hard-deprecations) and using it will raise errors like the following:
```
==> my_web_app
Compiling 62 files (.ex)
warning: Application.get_env/2 is discouraged in the module body, use Application.compile_env/3 instead
│
6 │   if Application.get_env(:my_persistence_app, :sql_sandbox) do
│                  ~
│
└─ lib/my_web_app/endpoint.ex:6:18: MyWebApp.Endpoint (module)
```
Related to:
- https://github.com/elixir-wallaby/wallaby/issues/761
- https://github.com/elixir-wallaby/wallaby/pull/762
> Update configuration example for umbrella apps

- .github/dependabot.yml
- .github/workflows/ci.yml
💁 These changes configure [Dependabot](https://docs.github.com/code-security/dependabot/) to keep Hex package and GitHub Actions dependencies up-to-date.
> Automatically update dependencies with Dependabot
