elixir-wallaby/wallaby

lib/wallaby/dsl/actions.ex, lib/wallaby/dsl/attributes.ex, lib/wallaby/dsl/matchers.ex, lib/wallaby/xpath.ex, test/support/pages/forms.html, test/wallaby/dsl_test.exs
basic interactions with checkboxes.
=> Allow interactions with checkboxes

lib/wallaby/dsl/finders.ex, test/support/pages/wait.html, test/test_helper.exs, test/wallaby/dsl_test.exs
The max wait time should probably be configurable...
=> Wait for elements to be visible

README.md
=> Update to correct module name

README.md, lib/wallaby/node.ex, lib/wallaby/xpath.ex, mix.exs, test/support/pages/select_boxes.html, test/wallaby/node_test.exs
It's all in the name! Ask @bomatson or I if any questions.
=> New feature: Support for Selecting an Option from a Select Box

README.md
Hoping this will help people save some time :D
=> Instruct users to enable server in test.exs

lib/wallaby/driver.ex, lib/wallaby/session.ex, test/wallaby/finders/title_test.exs
This provides the driver and user api for finding the title for the current page.
=> Add title function for getting page titles

lib/wallaby.ex
Allow users to configure the pool size via configuration values.
=> Configurable pool size

README.md, lib/wallaby/server.ex
Pretty simple change but allows customisation of the phantomjs process that Wallaby creates.
=> Adds a phantomjs_args config option to allow arguments to be passed to phantomjs.

README.md, lib/wallaby.ex, lib/wallaby/server.ex, priv/run_phantom.sh, test/wallaby/phantom/configure_test.exs
This PR allows users to specify an explicit path to phantomjs
Closes #80
=> Allow configurable phantomjs path

lib/wallaby/dsl/actions.ex, lib/wallaby/exceptions.ex, lib/wallaby/node/query.ex, lib/wallaby/xpath.ex, test/support/fixtures/file.txt, test/support/pages/forms.html, test/wallaby/dsl/actions/file_test.exs, test/wallaby/exceptions/query_error_test.exs
=> Adds support for HTML file input form fields

test/support/pages/forms.html, test/wallaby/browser/click_test.exs
=> Test for clicking invisible elements.

lib/wallaby/browser.ex, lib/wallaby/session.ex, test/support/pages/page_1.html, test/wallaby/browser/has_text_test.exs, test/wallaby/browser/send_text_test.exs, test/wallaby/browser/text_test.exs
Backwards compatibility fixes for the new api.
=> Backwards compatability fixes.

.travis.yml, lib/wallaby/element.ex, lib/wallaby/exceptions.ex, lib/wallaby/query.ex, mix.exs, mix.lock
Fixing some dialyzer issues and adding a dialyzer task for travisci.
=> Dialyzer exception issues

lib/wallaby/browser.ex, lib/wallaby/exceptions.ex, lib/wallaby/phantom/driver.ex, test/wallaby/browser/cookies_test.exs
This is an initial stab at setting and listing cookies in the browser. I still need to add some error handling but after that it should be good.
=> Initial cookies api

README.md
Although it's quite easy to setup, I thought it'd be nice to
mention the basic setup for people who want to get hacking :)
=> Mention development setup in the README

README.md
=> Reword AcceptanceCase to FeatureCase

CHANGELOG.md
* Hope I haven't forgotten anything user facing :)
=> Basic Changelog

mix.exs
Can't seem to find a web folder, so I guess it's not needed :)
=> Remove unused web from compile paths

integration_test/cases/browser/click_button_test.exs, integration_test/cases/browser/file_test.exs, integration_test/cases/browser/find_test.exs, integration_test/cases/browser/screenshot_test.exs, integration_test/cases/browser/select_test.exs, lib/wallaby/browser.ex
This PR removes the deprecated version of find.
=> Remove deprecated version of find.

integration_test/cases/browser/attr_test.exs, lib/wallaby/browser.ex
Remove deprecated version of attr/2
=> Remove deprecated attr/2

integration_test/cases/browser/find_test.exs, integration_test/cases/query_test.exs, lib/wallaby/browser.ex
Just like the title says. Removes the deprecated version of all.
=> Remove deprecated versions of all

.travis.yml
* Was accidentally removed as part of #198
=> Reinstate coveralls test coverage reporting

mix.exs
=> Update the maintainers list 🎉

lib/wallaby/browser.ex
=> Remove get_current_url

lib/wallaby/browser.ex
=> Remove deprecated set_window_size

README.md
Updates the README to reflect the new api and to help show a more consistent way to write tests. I'd still like to add a section specifically for page modules at some point but we can do that later.
=> Update README documentation.

CHANGELOG.md
I'm not actually sure what the protocol for updating the changelog should be. If there is a better way to manage this then please let me know :)
=> Update CHANGELOG.md for 0.17 release

.gitignore, .travis.yml, README.md, mix.exs, mix.lock
In an effort to up the documentation I wanted to add inch_ex to see where documentation was still missing so we can give some good documentation i.e. most importantly `Browser` and `Query`
Should probably also open an issue about that :)
=> inch ex badge and CI integration

lib/wallaby/experimental/chrome.ex
This PR sends the correct BEAM metadata that we need to make ecto sandboxes work correctly
with concurrent tests and chrome.
This fixes #281
=> Add beam metadata to chrome user agent

.tool-versions, .travis.yml, integration_test/cases/browser/find_test.exs, integration_test/support/test_server.ex
(will most likely fail, see if we can fix it otherwise tell the good folks at elixir)
=> Elixir 1.5.0 rc2 try

test/wallaby/phantom/configure_test.exs
This updates `Wallaby.Phantom.ConfigureTest` to use the SettingsTestHelpers. It removes the environment reset logic from the test and makes it easier to focus on the purpose of the tests.
=> Update ConfigureTest to use SettingsTestHelpers

integration_test/cases/browser/screenshot_test.exs, lib/wallaby/browser.ex
Basedon @aaronrenner's suggestion on https://github.com/keathley/wallaby/pull/313
@aaronrenner I'm not sure how to update the typespec - feel like helping?
=> Use a keyword argument list for options here

.tool-versions, .travis.yml
Just making sure we test against the latest elixir version
=> Test against Elixir 1.5.2

CHANGELOG.md, README.md, mix.exs
Updating release notes and version numbers for 0.19.2.
=> Prep for 0.19.2 release

README.md
Common setups and troubleshooting for assets in phoenix.
Closes #330.
=> Add information about assets to phoenix setup.

lib/wallaby/session.ex
=> Removes set_window_size/3 from Wallaby.Session

README.md
This updates the version stated in the setup section to the current version.
v0.19.2 -> v0.20.0
=> Update package version in README

README.md, integration_test/cases/browser/window_size_test.exs, lib/wallaby/experimental/chrome.ex, lib/wallaby/experimental/selenium.ex, lib/wallaby/phantom/driver.ex
Addresses #152 
@keathley @PragTob @aaronrenner Let me know what you think.
Thanks!
=> Option to configure default window size

.travis.yml, lib/wallaby/driver/process_workspace/server.ex, lib/wallaby/phantom/server.ex
This PR solves #410 
Just followed the previous convention and added the 3 latest versions.
=> Update .travis.yaml to include the 3 latest elixir versions

README.md, lib/wallaby/experimental/chrome.ex, lib/wallaby/experimental/chrome/chromedriver.ex, mix.lock
Allow for Chromedriver binary to be specified by
```
config :wallaby, chromedriver: "<my/path/to/chromedriver>"
```
Any feedback very welcome :-)
=> Configure chromedriver path

lib/wallaby/browser.ex
This PR is meant to be a replacement for #348. Once this is merged, #348 can be closed.
cc/ @michallepicki
=> Documentation on known issues with Emoji and ChromeDriver

CHANGELOG.md, README.md, mix.exs
This bumps the versions for the next release.
(I can't push straight to master)
=> Bump v0.23.0

README.md
=> Document Selenium remote_url config option

lib/wallaby/browser.ex, lib/wallaby/element.ex
=> Clarify documentation regarding retrieving hidden element text.

lib/wallaby/httpclient.ex
This adds typespes to `Wallaby.HTTPClient` to help document its existing error returns and make it easier to figure out the error returns of higher layer functions.
=> Add typespecs for Wallaby.HTTPClient

.github/workflows/ci.yml, .github/workflows/inch.yml
These come preinstalled on ubuntu-latest now
=> Remove custom install of ChromeDriver and Selenium form GH Actions

README.md, lib/event_emitter.ex, lib/wallaby.ex, lib/wallaby/browser.ex, lib/wallaby/chrome.ex, lib/wallaby/driver.ex, lib/wallaby/exceptions.ex, lib/wallaby/helpers/key_codes.ex, lib/wallaby/query.ex, lib/wallaby/query/error_message.ex, lib/wallaby/query/xpath.ex, lib/wallaby/webdriver_client.ex, mix.exs
List of changes:
- Use common source url
- Fix typos
- Badges and more badges!
=> Misc doc changes

lib/wallaby/selenium.ex
Add ability to change remote_url for selenium driver from config.
=> Fix remote_url config option for selenium driver

README.md
Part 2 for testing LiveView with Wallaby async.
[Part 1](https://github.com/elixir-wallaby/wallaby/pull/676)
=> Adds a note about the on_mount hook for async LiveView testing
